### ISSUE TITLE
When running pytest-pretty in github action the output is still standard pytest

### ISSUE THREAD

**Issue by greenomy-matteo** [samuelcolvin/pytest-pretty#13]
Hello, i've added in my yml the indication to install pytest-pretty

`        pip install flake8 pytest rich pytest-pretty 
`

and I call pytest as

```
    - name: Test with pytest
      run: |
        pytest .
      env:

```

but the output is the same as what what i had before. Am I doing something wrong?
